name: vbocp
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - matplotlib
  - gmsh
  - pyyaml
  - pytorch  # solo CPU per ora - GPU quando servira' per GNN/training piu' pesante
  - cpuonly
  - pip
  - pip:
      - pypolydim
